<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'TBLS',
  'author' => 'Mariano Bonilla',
  'description' => 'Contiene las Tablas simples (Codigo y Nombre) que son Cross-Modulo',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'TablasGenerales',
  'published_date' => '2018-08-08 18:30:24',
  'type' => 'module',
  'version' => 1533753024,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'TablasGenerales',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'TBLS_EstadoCivil',
      'class' => 'TBLS_EstadoCivil',
      'path' => 'modules/TBLS_EstadoCivil/TBLS_EstadoCivil.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'TBLS_Localidades',
      'class' => 'TBLS_Localidades',
      'path' => 'modules/TBLS_Localidades/TBLS_Localidades.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'TBLS_Nacionalidades',
      'class' => 'TBLS_Nacionalidades',
      'path' => 'modules/TBLS_Nacionalidades/TBLS_Nacionalidades.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'TBLS_Paises',
      'class' => 'TBLS_Paises',
      'path' => 'modules/TBLS_Paises/TBLS_Paises.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'TBLS_Profesiones',
      'class' => 'TBLS_Profesiones',
      'path' => 'modules/TBLS_Profesiones/TBLS_Profesiones.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'TBLS_Provincias',
      'class' => 'TBLS_Provincias',
      'path' => 'modules/TBLS_Provincias/TBLS_Provincias.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TBLS_EstadoCivil',
      'to' => 'modules/TBLS_EstadoCivil',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TBLS_Localidades',
      'to' => 'modules/TBLS_Localidades',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TBLS_Nacionalidades',
      'to' => 'modules/TBLS_Nacionalidades',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TBLS_Paises',
      'to' => 'modules/TBLS_Paises',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TBLS_Profesiones',
      'to' => 'modules/TBLS_Profesiones',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TBLS_Provincias',
      'to' => 'modules/TBLS_Provincias',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
);